---
title: "5.May_Vann_try"
output: html_document
date: "2023-05-02"
---
## Tutorial:
https://cran.r-project.org/web/packages/ggVennDiagram/vignettes/using-ggVennDiagram.html
and
https://github.com/hms-dbmi/UpSetR
https://www.rdocumentation.org/packages/UpSetR/versions/1.4.0/topics/upset
```{r setup, include=FALSE}
library(ggplot2)
library(sf)
library(venn)
library(cowplot)

library(ggVennDiagram)
```
# Import data
```{r}
data_ERR_same <- read.table("../A_Datas/For_COMP/COMP_ALL_same.txt", header = TRUE, sep = "\t")
data_ERR_diff <- read.table("../A_Datas/For_COMP/COMP_ALL_diff.txt", header = TRUE, sep = "\t")
data_ERR_masked <- read.table("../A_Datas/For_COMP/COMP_ALL_masked.txt", header = TRUE, sep = "\t")

#data_ALL_same <- read.table("../A_Datas/For_COMP/COMP_ALL_same.txt", header = TRUE, sep = "\t")
#data_ALL_diff <- read.table("../A_Datas/For_COMP/COMP_ALL_same.txt", header = TRUE, sep = "\t")
#data_ALL_masked <- read.table("../A_Datas/For_COMP/COMP_ALL_same.txt", header = TRUE, sep = "\t")
```

```{r}
transform_to_list <- function(data, flag_value) {
  x_list <- list(
    AF = data$ID_POS[data$Flag_AF == flag_value],
    SB = data$ID_POS[data$Flag_SB == flag_value],
    COV = data$ID_POS[data$Flag_COV == flag_value]
  )
  venn_type_data <- process_data(Venn(x_list))
  return(venn_type_data)
}
```


```{r}
# data processing
Err_same <- transform_to_list(data_ERR_same, "True")
Err_same_F <- transform_to_list(data_ERR_same, "False")

Err_diff <- transform_to_list(data_ERR_diff, "True")
Err_diff_F <- transform_to_list(data_ERR_diff, "False")

Err_masked <- transform_to_list(data_ERR_masked, "True")
Err_masked_F <- transform_to_list(data_ERR_masked, "False")
```

## For same nucleotide
```{r}
data_ERR_same$Flag_AF <- as.logical(data_ERR_same$Flag_AF)
data_ERR_same$Flag_SB <- as.logical(data_ERR_same$Flag_SB)
data_ERR_same$Flag_COV <- as.logical(data_ERR_same$Flag_COV)

data_ERR_count_F <- sum(!data_ERR_same$Flag_AF & !data_ERR_same$Flag_SB & !data_ERR_same$Flag_COV)
data_ERR_count <- sum(data_ERR_same$Flag_AF & data_ERR_same$Flag_SB & data_ERR_same$Flag_COV)
```

```{r}
请重新为我修改最浅的颜色介于"#FFFFFF",
"#FFEBEB",


"#FFEBEB"
"#FFE1E1"
"#FFB2B2"
"#FF9999"
"#FF7F7F"
"#E04C4C"
"#FF6666"
"#E04C4C"
"#C53232"
"#A51919"
"#800000"
```

```{r}
# 自定义颜色
manual_colors <- c("AF" = "orange", "SB" = "steelblue", "COV" = "red")

# 绘制第一个图形
p1 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(Err_same)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(Err_same), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(Err_same)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR_same)*100, 3), "%)")),
                data = venn_region(Err_same),
                size = 3) +  theme_void()+ 
  scale_fill_gradientn(colors = c("#FFEBEB",
"#FFE1E1",
"#FFB2B2",
"#FF9999",
"#FF7F7F",
"#E04C4C",
"#FF6666",
"#E04C4C",
"#C53232",
"#A51919",
"#800000"), 
                       values = c(0, 0.02, 0.04, 0.06, 0.08, 0.15, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 10000), guide = "none")+
  scale_color_manual(values = manual_colors)+
  labs(title = "Passed the threshold",
         # subtitle = "blank for now",
         # caption = Sys.Date()
       )+
  theme(panel.border = element_rect(colour = "grey", fill=NA, size=1),   # 给图加一个边框
  
        panel.background = element_rect(fill = "#FFEBEB")) +
  annotate(geom = 'text', label = paste0(data_ERR_count_F, " (", round(data_ERR_count_F/nrow(data_ERR_same)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -1.6, vjust = 1.5, size = 5)

# 绘制第二个图形
p2 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(Err_same_F)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(Err_same_F), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(Err_same_F)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR_same)*100, 3), "%)")),
                data = venn_region(Err_same_F),
                size = 3) +  theme_void()+ 
  scale_fill_gradientn(colors = c("#FFEBEB",
"#FFE1E1",
"#FFB2B2",
"#FF9999",
"#FF7F7F",
"#E04C4C",
"#FF6666",
"#E04C4C",
"#C53232",
"#A51919",
"#800000"), 
                       values = c(0, 0.02, 0.04, 0.06, 0.08, 0.15, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 10000), guide = "none")+
  scale_color_manual(values = manual_colors)+
  labs(title = "Unpassed the threshold",
         # subtitle = "blank for now",
         # caption = Sys.Date()
       )+
  theme(panel.border = element_rect(colour = "grey", fill=NA, size=1),   # 给图加一个边框
  
        panel.background = element_rect(fill = "#FF7F7F")) +
  annotate(geom = 'text', label = paste0(data_ERR_count, " (", round(data_ERR_count/nrow(data_ERR_same)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -0.9, vjust = 1.5, size = 5)

# 创建标题
# title <- ggdraw() + draw_label("Venn diagram of the indicator comparison")

# 在一个2 x 2的画布上显示四个图形
combined_plot <- plot_grid(p1, p2, nrow = 1, ncol = 2)

# 添加共享图例
legend <- cowplot::get_legend(
  ggplot() +
    geom_sf(aes(color = name), data = venn_setedge(Err_same), show.legend = TRUE, size = 2) +
    scale_color_manual(values = manual_colors) +
    theme_void() +
    labs(color = "Category") +
    theme(legend.direction = "horizontal")
)

# 将图形和图例组合在一起
final_plot <- plot_grid(
  title,
  combined_plot, 
  legend, 
  nrow = 3, 
  rel_heights = c(0.1, 1, 0.1), 
  align = "h", 
  axis = "l"
)

# 显示最终的图形
print(final_plot)
```

## For diff nucleotide
```{r}
data_ERR_diff$Flag_AF <- as.logical(data_ERR_diff$Flag_AF)
data_ERR_diff$Flag_SB <- as.logical(data_ERR_diff$Flag_SB)
data_ERR_diff$Flag_COV <- as.logical(data_ERR_diff$Flag_COV)

data_ERR_count_F <- sum(!data_ERR_diff$Flag_AF & !data_ERR_diff$Flag_SB & !data_ERR_diff$Flag_COV)
data_ERR_count <- sum(data_ERR_diff$Flag_AF & data_ERR_diff$Flag_SB & data_ERR_diff$Flag_COV)
```

```{r}
请重新为我修改最浅的颜色介于"#FFFFFF",
"#FFEBEB",


"#F5FFF5",
"#F0FFF0",
"#E6FFE6",
"#CCFFCC",
"#AAFFAA",
"#88FF88",
"#66FF66",
"#44FF44",
"#22FF22",
"#00FF00"

```

```{r}
# 自定义颜色
manual_colors <- c("AF" = "orange", "SB" = "steelblue", "COV" = "red")

# 绘制第一个图形
p1 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(Err_diff)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(Err_diff), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(Err_diff)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR_diff)*100, 3), "%)")),
                data = venn_region(Err_diff),
                size = 3) +  theme_void()+ 
  scale_fill_gradientn(colors = c("#F5FFF5",
"#F0FFF0",
"#E6FFE6",
"#CCFFCC",
"#AAFFAA",
"#88FF88",
"#66FF66",
"#44FF44",
"#22FF22",
"#00FF00"), 
                       values = c(0, 0.02, 0.04, 0.06, 0.08, 0.15, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 10000), guide = "none")+
  scale_color_manual(values = manual_colors)+
  labs(title = "Passed the threshold",
         # subtitle = "blank for now",
         # caption = Sys.Date()
       )+
  theme(panel.border = element_rect(colour = "grey", fill=NA, size=1),   # 给图加一个边框
  
        panel.background = element_rect(fill = "#AAFFAA")) +
  annotate(geom = 'text', label = paste0(data_ERR_count_F, " (", round(data_ERR_count_F/nrow(data_ERR_diff)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -0.9, vjust = 1.5, size = 5)

# 绘制第二个图形
p2 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(Err_diff_F)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(Err_diff_F), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(Err_diff_F)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR_diff)*100, 3), "%)")),
                data = venn_region(Err_diff_F),
                size = 3) +  theme_void()+ 
    scale_fill_gradientn(colors = c("#F5FFF5",
"#F0FFF0",
"#E6FFE6",
"#CCFFCC",
"#AAFFAA",
"#88FF88",
"#66FF66",
"#44FF44",
"#22FF22",
"#00FF00"), 
                       values = c(0, 0.02, 0.04, 0.06, 0.08, 0.15, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 10000), guide = "none")+
  scale_color_manual(values = manual_colors)+
  labs(title = "Unpassed the threshold",
         # subtitle = "blank for now",
         # caption = Sys.Date()
       )+
  theme(panel.border = element_rect(colour = "grey", fill=NA, size=1),   # 给图加一个边框
  
        panel.background = element_rect(fill = "#E6FFE6")) +
  annotate(geom = 'text', label = paste0(data_ERR_count, " (", round(data_ERR_count/nrow(data_ERR_diff)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -1.2, vjust = 1.5, size = 5)

# 创建标题
# title <- ggdraw() + draw_label("Venn diagram of the indicator comparison")

# 在一个2 x 2的画布上显示四个图形
combined_plot <- plot_grid(p1, p2, nrow = 1, ncol = 2)

# 添加共享图例
legend <- cowplot::get_legend(
  ggplot() +
    geom_sf(aes(color = name), data = venn_setedge(Err_diff), show.legend = TRUE, size = 2) +
    scale_color_manual(values = manual_colors) +
    theme_void() +
    labs(color = "Category") +
    theme(legend.direction = "horizontal")
)

# 将图形和图例组合在一起
final_plot <- plot_grid(
  title,
  combined_plot, 
  legend, 
  nrow = 3, 
  rel_heights = c(0.1, 1, 0.1), 
  align = "h", 
  axis = "l"
)

# 显示最终的图形
print(final_plot)
```

## 3. For viridian assembly masked
```{r}
data_ERR_masked$Flag_AF <- as.logical(data_ERR_masked$Flag_AF)
data_ERR_masked$Flag_SB <- as.logical(data_ERR_masked$Flag_SB)
data_ERR_masked$Flag_COV <- as.logical(data_ERR_masked$Flag_COV)

data_ERR_count_F <- sum(!data_ERR_masked$Flag_AF & !data_ERR_masked$Flag_SB & !data_ERR_masked$Flag_COV)
data_ERR_count <- sum(data_ERR_masked$Flag_AF & data_ERR_masked$Flag_SB & data_ERR_masked$Flag_COV)
```

```{r}
请重新为我修改最浅的颜色介于"#FFFFFF",
"#FFEBEB",


"#F5FFF5",
"#F0FFF0",
"#E6FFE6",
"#CCFFCC",
"#AAFFAA",
"#88FF88",
"#66FF66",
"#44FF44",
"#22FF22",
"#00FF00"

```

```{r}
# 自定义颜色
manual_colors <- c("AF" = "orange", "SB" = "steelblue", "COV" = "red")

# 绘制第一个图形
p1 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(Err_masked)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(Err_masked), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(Err_masked)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR_masked)*100, 3), "%)")),
                data = venn_region(Err_masked),
                size = 3) +  theme_void()+ 
  scale_fill_gradientn(colors = c("#F4FAFE","#EBF6FD","#E2F3FC","#D9EFFB","#ACDEF6","#A3DBF5","#9AD8F4","#91D4F3","#82C7F8","#6FBEF7","#5CB6F6","#499DF5"), 
                       values = c(0, 0.02, 0.04, 0.06, 0.08, 0.15, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 10000), guide = "none")+
  scale_color_manual(values = manual_colors)+
  labs(title = "Passed the threshold",
         # subtitle = "blank for now",
         # caption = Sys.Date()
       )+
  theme(panel.border = element_rect(colour = "grey", fill=NA, size=1),   # 给图加一个边框
  
        panel.background = element_rect(fill = "#F4FAFE")) +
  annotate(geom = 'text', label = paste0(data_ERR_count_F, " (", round(data_ERR_count_F/nrow(data_ERR_masked)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -1.3, vjust = 1.5, size = 5)

# 绘制第二个图形
p2 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(Err_masked_F)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(Err_masked_F), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(Err_masked_F)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR_masked)*100, 3), "%)")),
                data = venn_region(Err_masked_F),
                size = 3) +  theme_void()+ 
    scale_fill_gradientn(colors = c("#F4FAFE","#EBF6FD","#E2F3FC","#D9EFFB","#ACDEF6","#A3DBF5","#9AD8F4","#91D4F3","#82C7F8","#6FBEF7","#5CB6F6","#499DF5"), 
                       values = c(0, 0.02, 0.04, 0.06, 0.08, 0.15, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 10000), guide = "none")+
  scale_color_manual(values = manual_colors)+
  labs(title = "Unpassed the threshold",
         # subtitle = "blank for now",
         # caption = Sys.Date()
       )+
  theme(panel.border = element_rect(colour = "grey", fill=NA, size=1),   # 给图加一个边框
  
        panel.background = element_rect(fill = "#ACDEF6")) +
  annotate(geom = 'text', label = paste0(data_ERR_count, " (", round(data_ERR_count/nrow(data_ERR_masked)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -0.9, vjust = 1.5, size = 5)

# 创建标题
# title <- ggdraw() + draw_label("Venn diagram of the indicator comparison")

# 在一个2 x 2的画布上显示四个图形
combined_plot <- plot_grid(p1, p2, nrow = 1, ncol = 2)

# 添加共享图例
legend <- cowplot::get_legend(
  ggplot() +
    geom_sf(aes(color = name), data = venn_setedge(Err_diff), show.legend = TRUE, size = 2) +
    scale_color_manual(values = manual_colors) +
    theme_void() +
    labs(color = "Category") +
    theme(legend.direction = "horizontal")
)

# 将图形和图例组合在一起
final_plot <- plot_grid(
  title,
  combined_plot, 
  legend, 
  nrow = 3, 
  rel_heights = c(0.1, 1, 0.1), 
  align = "h", 
  axis = "l"
)

# 显示最终的图形
print(final_plot)
```