---
title: "5.May_Vann_try"
output: html_document
date: "2023-05-02"
---
## Tutorial:
https://cran.r-project.org/web/packages/ggVennDiagram/vignettes/using-ggVennDiagram.html
and
https://github.com/hms-dbmi/UpSetR
https://www.rdocumentation.org/packages/UpSetR/versions/1.4.0/topics/upset

# Import data
```{r}
data_ERR_AF <- read.table("../A_Datas/ERR_AF.txt", header = TRUE, sep = "\t")
data_ERR_SB <- read.table("../A_Datas/ERR_SB.txt", header = TRUE, sep = "\t")
data_ERR_COV <- read.table("../A_Datas/ERR_COV.txt", header = TRUE, sep = "\t")
data_ALL_AF <- read.table("../A_Datas/ALL_AF.txt", header = TRUE, sep = "\t")
data_ALL_SB <- read.table("../A_Datas/ALL_SB.txt", header = TRUE, sep = "\t")
data_ALL_COV <- read.table("../A_Datas/ALL_COV.txt", header = TRUE, sep = "\t")

head(data_ERR_AF);head(data_ERR_SB);head(data_ERR_COV);head(data_ALL_AF);head(data_ALL_SB);head(data_ALL_COV)
```
```{r}
x_ERR <- list(
  AF_ERR = data_ERR_AF$Position[data_ERR_AF$Flag == "True"],
  SB_ERR = data_ERR_SB$Position[data_ERR_SB$Flag == "True"],
  COV_ERR = data_ERR_COV$Position[data_ERR_COV$Flag == "True"]
)

x_ALL <- list(
  AF_ALL = data_ALL_AF$POS[data_ALL_AF$Flag == "True"],
  SB_ALL = data_ALL_SB$POS[data_ALL_SB$Flag == "True"],
  COV_ALL = data_ALL_COV$POS[data_ALL_COV$Flag == "True"]
)

combined_list <- c(x_ERR, x_ALL)
```
## Vis
```{r setup, include=FALSE}
library(ggplot2)
library(sf)
library(venn)
library(cowplot)
```


```{r}
ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_err)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_err), show.legend = TRUE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_err)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR_COV)*100, 3), "%)")),
                data = venn_region(data_err),
                size = 3) +
  scale_fill_gradient(low = "#F4FAFE", high = "skyblue")+
  scale_color_manual(values = c("AF" = "orange", "SB" = "steelblue", "COV" = "red"))+
  theme_void()+ 
  labs(title = "Error position's Venn Diagram",
         subtitle = "blank for now",
         caption = Sys.Date()) +
  theme(legend.position = "bottom")  # 添加图例在底部的设置

```
```{r}
x_ERR <- list(
  AF = data_ERR_AF$Position[data_ERR_AF$Flag == "True"],
  SB = data_ERR_SB$Position[data_ERR_SB$Flag == "True"],
  COV = data_ERR_COV$Position[data_ERR_COV$Flag == "True"]
)

x_ALL <- list(
  AF = data_ALL_AF$POS[data_ALL_AF$Flag == "True"],
  SB = data_ALL_SB$POS[data_ALL_SB$Flag == "True"],
  COV = data_ALL_COV$POS[data_ALL_COV$Flag == "True"]
)
```

```{r}
# 计算和处理数据
data_err <- process_data(Venn(x_ERR))
data_all <- process_data(Venn(x_ALL))

# 自定义颜色
manual_colors <- c("AF" = "orange", "SB" = "steelblue", "COV" = "red")

# 绘制第一个图形
p1 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_err)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_err), show.legend = TRUE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_err)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR_COV)*100, 3), "%)")),
                data = venn_region(data_err),
                size = 3) +
  scale_fill_gradient(low = "#F4FAFE", high = "skyblue")+
  scale_color_manual(values = manual_colors)+
  theme_void()+ 
  labs(title = "Error positions' Venn Diagram",
         subtitle = "blank for now",
         caption = Sys.Date()) +
  theme(legend.position = "bottom")  # 添加图例在底部的设置

# 绘制第二个图形
p2 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_all)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_all), show.legend = TRUE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_all)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ALL_COV)*100, 3), "%)")),
                data = venn_region(data_all),
                size = 3) +
  scale_fill_gradient(low = "#F4FAFE", high = "skyblue")+
  scale_color_manual(values = manual_colors)+
  theme_void()+ 
  labs(title = "All positions' Venn Diagram",
         subtitle = "blank for now",
         caption = Sys.Date()) +
  theme(legend.position = "bottom")  # 添加图例在底部的设置

# 在一个1 x 2的画布上显示两个图形
plot_grid(p1, p2, ncol = 2)


```


# !!!! FINAL
```{r}
# 计算和处理数据
data_err <- process_data(Venn(x_ERR))
data_all <- process_data(Venn(x_ALL))

# 自定义颜色
manual_colors <- c("AF" = "orange", "SB" = "steelblue", "COV" = "red")

# 绘制第一个图形
p1 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_err)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_err), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_err)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR_COV)*100, 3), "%)")),
                data = venn_region(data_err),
                size = 3) +  theme_void()+ 
  scale_fill_gradient(low = "#F4FAFE", high = "skyblue") +
  scale_color_manual(values = manual_colors)+
  labs(title = "Error positions' Venn Diagram",
         subtitle = "blank for now",
         caption = Sys.Date())

# 绘制第二个图形
p2 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_all)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_all), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_all)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ALL_COV)*100, 3), "%)")),
                data = venn_region(data_all),
                size = 3) +  theme_void()+ 
  scale_fill_gradient(low = "#F4FAFE", high = "skyblue") +
  scale_color_manual(values = manual_colors)+
  labs(title = "All positions' Venn Diagram",
         subtitle = "blank for now",
         caption = Sys.Date())

# 在一个1 x 2的画布上显示两个图形
combined_plot <- plot_grid(p1, p2, ncol = 2)

# 添加共享图例
legend <- cowplot::get_legend(
  ggplot() +
    geom_sf(aes(color = name), data = venn_setedge(data_all), show.legend = TRUE, size = 2) +
    scale_color_manual(values = manual_colors) +
    theme_void() +
    labs(color = "Category") +
    theme(legend.direction = "horizontal")
)

# 将图形和图例组合在一起
final_plot <- plot_grid(
  combined_plot, 
  NULL, 
  legend, 
  nrow = 3, 
  rel_heights = c(2, 0.01, 0.1), 
  align = "h", 
  axis = "l"
)

# 显示最终的图形
print(final_plot)


```
# Some other tests
```{r setup, include=FALSE}
library(UpSetR)
```

```{r}

# 从数据框 combined_df 中删除 COV_ALL 列
combined_df <- combined_list[-length(combined_list)]

upset(fromList(combined_df), sets.bar.color = "#56B4E9",
      order.by = "freq", # empty.intersections = "on",
      set_size.show = T,
      sets.x.label = "Set Size",
      mainbar.y.label = "Intersection Size",
      mb.ratio = c(0.55, 0.45)
      )
```

```{r}
vennpie(venndetail(combined_list))
```
```{r}
venn <- venndetail(combined_list)

plot(venn,type = "upset")
plot(venn, type = "vennpie")
```

