---
title: "5.May_Vann_try"
output: html_document
date: "2023-05-02"
---
## Tutorial:
https://cran.r-project.org/web/packages/ggVennDiagram/vignettes/using-ggVennDiagram.html
and
https://github.com/hms-dbmi/UpSetR
https://www.rdocumentation.org/packages/UpSetR/versions/1.4.0/topics/upset
```{r setup, include=FALSE}
library(ggplot2)
library(sf)
library(venn)
library(cowplot)

library(ggVennDiagram)
```
# Import data
```{r}
data_ERR_same <- read.table("../../A_Datas/For_COMP/COMP_ALL_same.txt", header = TRUE, sep = "\t")
data_ERR_diff <- read.table("../../A_Datas/For_COMP/COMP_ALL_diff.txt", header = TRUE, sep = "\t")

data_ERR_masked <- read.table("../../A_Datas/For_COMP/COMP_ALL_masked.txt", header = TRUE, sep = "\t")
```

```{r}
transform_to_list <- function(data, flag_value) {
  x_list <- list(
    AF = data$ID_POS[data$Flag_AF == flag_value],
    SB = data$ID_POS[data$Flag_SB == flag_value],
    COV = data$ID_POS[data$Flag_COV == flag_value]
  )
  venn_type_data <- process_data(Venn(x_list))
  return(venn_type_data)
}
```


```{r}
# data processing
Err_same <- transform_to_list(data_ERR_same, 1)

Err_diff <- transform_to_list(data_ERR_diff, 1)

Err_masked <- transform_to_list(data_ERR_masked, 1)
```

## For same nucleotide
```{r}
data_ERR_same$Flag_AF <- as.logical(data_ERR_same$Flag_AF)
data_ERR_same$Flag_SB <- as.logical(data_ERR_same$Flag_SB)
data_ERR_same$Flag_COV <- as.logical(data_ERR_same$Flag_COV)

data_ERR_count_F <- sum(!data_ERR_same$Flag_AF & !data_ERR_same$Flag_SB & !data_ERR_same$Flag_COV)
data_ERR_count <- sum(data_ERR_same$Flag_AF & data_ERR_same$Flag_SB & data_ERR_same$Flag_COV)
```

```{r}
format_count <- function(count) {
  result <- ifelse(count >= 1e9, paste0(round(count / 1e9, 2), "B"),
            ifelse(count >= 1e6, paste0(round(count / 1e6, 2), "M"),
            ifelse(count >= 1e3, paste0(round(count / 1e3, 2), "K"),
            as.character(count))))
  return(result)
}
```

```{r}
AF <- 15914808
SB <- 10584406
COV <- 320151144
AF_SB <- 26725181
AF_COV <- 1021777
SB_COV <- 141549
ALL <- 367633
ALL_UN <-3377979636
NB_all <- AF+SB+COV+AF_SB+AF_COV+SB_COV+ALL+ALL_UN

Err_same@region[["count"]][1] <- AF
Err_same@region[["count"]][2] <- SB
Err_same@region[["count"]][3] <- COV
Err_same@region[["count"]][4] <- AF_SB
Err_same@region[["count"]][5] <- AF_COV
Err_same@region[["count"]][6] <- SB_COV
Err_same@region[["count"]][7] <- ALL
```

```{r}
# 自定义颜色
manual_colors <- c("AF" = "#BEBBDC", "SB" =  "#8ECFC9", "COV" = "#FFD700")

# 创建标题
title <- ggdraw() + draw_label("Same nucleotide")

# 创建共享图例
legend <- cowplot::get_legend(
  ggplot() +
    geom_sf(aes(color = name), data = venn_setedge(Err_same), show.legend = TRUE, size = 10, lwd = 1.5) +
    scale_color_manual(values = manual_colors) +
    theme_void() +
    labs(color = "Category") +
    theme(legend.direction = "horizontal")
)

# 绘制图形并将图形和图例组合在一起
final_plot <- plot_grid(
  title,
  ggplot() +
    geom_sf(aes(fill = count), data = venn_region(Err_same)) +
    geom_sf(aes(color = name), data = venn_setedge(Err_same), show.legend = FALSE, lwd = 1.5) +
    geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(Err_same)) +
    geom_sf_label(aes(label = paste0(format_count(count), " (", round(count/NB_all*100, 3), "%)")),
                data = venn_region(Err_same),
                size = 5) +  theme_void()+ 
    scale_fill_gradientn(colors = c("#FFEBEB",
"#FFE1E1",
"#FFB2B2",
"#FF9999",
"#FF7F7F",
"#E04C4C",
"#FF6666",
"#FF6666",
"#E04C4C",
"#C53232",
"#A51919",
"#800000"), 
                       values = c(0, 0.01, 0.04, 0.08, 0.1, 0.3, 0.5, 0.7, 0.8, 0.9, 1), limits = c(0, 3400000000), guide = "none")+
    scale_color_manual(values = manual_colors)+
    theme(panel.border = element_rect(colour = "white", fill=NA, size=1.5),   # 给图加一个边框
        panel.background = element_rect(fill = "#C53232")),
    # annotate(geom = 'text', label = paste0(data_ERR_count_F, " (", round(data_ERR_count_F/nrow(data_ERR_same)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -1.2, vjust = 1.5, size = 5),
  legend, 
  nrow = 3, 
  rel_heights = c(0.1, 1, 0.1), 
  align = "h", 
  axis = "l"
)

# 显示最终的图形
print(final_plot)
```


## For diff nucleotide
```{r}
AF <- 24739
SB <- 341
COV <- 2021
AF_SB <- 77001
AF_COV <- 1713
SB_COV <- 166
ALL <- 9363
ALL_UN <- 4839
NB_all <- AF+SB+COV+AF_SB+AF_COV+SB_COV+ALL+ALL_UN

Err_diff@region[["count"]][1] <- AF
Err_diff@region[["count"]][2] <- SB
Err_diff@region[["count"]][3] <- COV
Err_diff@region[["count"]][4] <- AF_SB
Err_diff@region[["count"]][5] <- AF_COV
Err_diff@region[["count"]][6] <- SB_COV
Err_diff@region[["count"]][7] <- ALL
```


```{r}
# 自定义颜色
manual_colors <- c("AF" = "#BEBBDC", "SB" =  "#8ECFC9", "COV" = "#FFD700")

# 创建标题
title <- ggdraw() + draw_label("Different nucleotide")

# 创建共享图例
legend <- cowplot::get_legend(
  ggplot() +
    geom_sf(aes(color = name), data = venn_setedge(Err_diff), show.legend = TRUE, size = 10, lwd = 1.5) +
    scale_color_manual(values = manual_colors) +
    theme_void() +
    labs(color = "Category") +
    theme(legend.direction = "horizontal")
)

# 绘制图形并将图形和图例组合在一起
final_plot <- plot_grid(
  title,
  ggplot() +
    geom_sf(aes(fill = count), data = venn_region(Err_diff)) +
    geom_sf(aes(color = name), data = venn_setedge(Err_diff), show.legend = FALSE, lwd = 1.5) +
    geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(Err_diff)) +
    geom_sf_label(aes(label = paste0(format_count(count), " (", round(count/NB_all*100, 3), "%)")),
                data = venn_region(Err_diff),
                size = 5) +  theme_void()+ 
    scale_fill_gradientn(colors = c("#F5FFF5",
"#F0FFF0",
"#E6FFE6",
"#CCFFCC",
"#AAFFAA",
"#88FF88",
"#66FF66",
"#44FF44",
"#22FF22",
"#00FF00"), 
                       values = c(0, 0.01, 0.04, 0.08, 0.1, 0.3, 0.5, 0.7, 0.9, 1), limits = c(0, 90000), guide = "none")+
    scale_color_manual(values = manual_colors)+
    theme(panel.border = element_rect(colour = "white", fill=NA, size=1.5),   # 给图加一个边框
        panel.background = element_rect(fill = "#F5FFF5")) ,
    #annotate(geom = 'text', label = paste0(data_ERR_count_F, " (", round(data_ERR_count_F/nrow(data_ERR_same)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -1.2, vjust = 1.5, size = 5),
  legend, 
  nrow = 3, 
  rel_heights = c(0.1, 1, 0.1), 
  align = "h", 
  axis = "l"
)

# 显示最终的图形
print(final_plot)
```


## 3. For viridian assembly masked
```{r}
AF <- 223475
SB <- 5520
COV <- 75904068
AF_SB <- 69090
AF_COV <- 66826
SB_COV <- 40259
ALL <- 49100
ALL_UN <- 16217155
NB_all <- AF+SB+COV+AF_SB+AF_COV+SB_COV+ALL+ALL_UN

Err_masked@region[["count"]][1] <- AF
Err_masked@region[["count"]][2] <- SB
Err_masked@region[["count"]][3] <- COV
Err_masked@region[["count"]][4] <- AF_SB
Err_masked@region[["count"]][5] <- AF_COV
Err_masked@region[["count"]][6] <- SB_COV
Err_masked@region[["count"]][7] <- ALL
```

```{r}
# 自定义颜色
manual_colors <- c("AF" = "#BEBBDC", "SB" =  "#8ECFC9", "COV" = "#FFD700")

# 创建标题
title <- ggdraw() + draw_label("Viridian assembly masked")

# 创建共享图例
legend <- cowplot::get_legend(
  ggplot() +
    geom_sf(aes(color = name), data = venn_setedge(Err_masked), show.legend = TRUE, size = 10, lwd = 1.5) +
    scale_color_manual(values = manual_colors) +
    theme_void() +
    labs(color = "Category") +
    theme(legend.direction = "horizontal")
)

# 绘制图形并将图形和图例组合在一起
final_plot <- plot_grid(
  title,
  ggplot() +
    geom_sf(aes(fill = count), data = venn_region(Err_masked)) +
    geom_sf(aes(color = name), data = venn_setedge(Err_masked), show.legend = FALSE, lwd = 1.5) +
    geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(Err_masked)) +
    geom_sf_label(aes(label = paste0(format_count(count), " (", round(count/NB_all*100, 3), "%)")),
                data = venn_region(Err_masked),
                size = 5) +  theme_void()+ 
    scale_fill_gradientn(colors = c("#F4FAFE","#EBF6FD","#E2F3FC","#D9EFFB","#ACDEF6","#A3DBF5","#9AD8F4","#91D4F3","#82C7F8","#6FBEF7","#5CB6F6","#499DF5"), 
                  values = c(0, 0.01, 0.04, 0.08, 0.1, 0.3, 0.5, 0.7, 0.9, 1), limits = c(0, 76000000), guide = "none")+
    scale_color_manual(values = manual_colors)+
    theme(panel.border = element_rect(colour = "white", fill=NA, size=1.5),   # 给图加一个边框
        panel.background = element_rect(fill = "#ACDEF6")),
    #annotate(geom = 'text', label = paste0(data_ERR_count_F, " (", round(data_ERR_count_F/nrow(data_ERR_same)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -1.2, vjust = 1.5, size = 5),
  legend, 
  nrow = 3, 
  rel_heights = c(0.1, 1, 0.1), 
  align = "h", 
  axis = "l"
)

# 显示最终的图形
print(final_plot)
```
