---
title: "5.May_Vann_try"
output: html_document
date: "2023-05-02"
---
## Tutorial:
https://cran.r-project.org/web/packages/ggVennDiagram/vignettes/using-ggVennDiagram.html
and
https://github.com/hms-dbmi/UpSetR
https://www.rdocumentation.org/packages/UpSetR/versions/1.4.0/topics/upset

# Import data
```{r}
# data_ERR <- read.table("../../A_Datas/ERR_POS.txt", header = TRUE, sep = "\t")
# data_ALL <- read.table("../../A_Datas/ALL_POS.txt", header = TRUE, sep = "\t")
data_ERR <- read.table("../../A_Datas/ERR_POS_all.txt", header = TRUE, sep = "\t")
data_ALL <- read.table("../../A_Datas/ALL_POS_all.txt", header = TRUE, sep = "\t")
```


```{r}
x_ERR <- list(
  AF = data_ERR$ID_POS[data_ERR$Flag_AF == "True"],
  SB = data_ERR$ID_POS[data_ERR$Flag_SB == "True"],
  COV = data_ERR$ID_POS[data_ERR$Flag_COV == "True"]
)

x_ALL <- list(
  AF = data_ALL$ID_POS[data_ALL$Flag_AF == "True"],
  SB = data_ALL$ID_POS[data_ALL$Flag_SB == "True"],
  COV = data_ALL$ID_POS[data_ALL$Flag_COV == "True"]
)

x_ERR_F <- list(
  AF = data_ERR$ID_POS[data_ERR$Flag_AF == "False"],
  SB = data_ERR$ID_POS[data_ERR$Flag_SB == "False"],
  COV = data_ERR$ID_POS[data_ERR$Flag_COV == "False"]
)

x_ALL_F <- list(
  AF = data_ALL$ID_POS[data_ALL$Flag_AF == "False"],
  SB = data_ALL$ID_POS[data_ALL$Flag_SB == "False"],
  COV = data_ALL$ID_POS[data_ALL$Flag_COV == "False"]
)

combined_list <- c(x_ERR, x_ALL)
```
## Vis
```{r setup, include=FALSE}
library(ggplot2)
library(sf)
library(venn)
library(cowplot)

library(ggVennDiagram)
```


## 1. For F
```{r}
# 计算和处理数据
data_err <- process_data(Venn(x_ERR))
data_all <- process_data(Venn(x_ALL))

data_err_F <- process_data(Venn(x_ERR_F))
data_all_F <- process_data(Venn(x_ALL_F))
```

```{r}
data_ALL$Flag_AF <- as.logical(data_ALL$Flag_AF)
data_ALL$Flag_SB <- as.logical(data_ALL$Flag_SB)
data_ALL$Flag_COV <- as.logical(data_ALL$Flag_COV)

data_ERR$Flag_AF <- as.logical(data_ERR$Flag_AF)
data_ERR$Flag_SB <- as.logical(data_ERR$Flag_SB)
data_ERR$Flag_COV <- as.logical(data_ERR$Flag_COV)

data_ERR_F_count <- sum(!data_ERR$Flag_AF & !data_ERR$Flag_SB & !data_ERR$Flag_COV)
data_ALL_F_count <- sum(!data_ALL$Flag_AF & !data_ALL$Flag_SB & !data_ALL$Flag_COV)

data_ERR_count <- sum(data_ERR$Flag_AF & data_ERR$Flag_SB & data_ERR$Flag_COV)
data_ALL_count <- sum(data_ALL$Flag_AF & data_ALL$Flag_SB & data_ALL$Flag_COV)
```


```{r}
ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_err)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_err), show.legend = TRUE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_err)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR)*100, 3), "%)")),
                data = venn_region(data_err),
                size = 3) +
  scale_fill_gradientn(colors = c("#F4FAFE","#CFE9FC","#BCE1FB","#A8D8FA","#95D0F9","skyblue","#82C7F8","#6FBEF7","#5CB6F6","#499DF5"), 
                       values = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 135000))+

  scale_color_manual(values = c("AF" = "orange", "SB" = "steelblue", "COV" = "red")) +
  theme_void() +
  labs(title = "Error position's Venn Diagram",
       caption = Sys.Date()) +
  theme(legend.position = "bottom",  # 添加图例在底部的设置
        panel.border = element_rect(colour = "black", fill=NA, size=1)) +  # 给图加一个边框
  annotate(geom = 'text', label = paste0(data_ALL_count, " (", round(data_ALL_count/nrow(data_ERR)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -1, vjust = 1.5, size = 5)
```

# !!!! FINAL
```{r}
# 自定义颜色
manual_colors <- c("AF" = "orange", "SB" = "steelblue", "COV" = "red")

# 绘制第一个图形
p1 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_err)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_err), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_err)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR)*100, 3), "%)")),
                data = venn_region(data_err),
                size = 3) +  theme_void()+ 
  scale_fill_gradientn(colors = c("#F4FAFE", "#2DB600", "#63C600", "#A0D600", "#E6E600", "#E8C32E", "#EBB25E", "#EDB48E", "#F0C9C0", "#F2F2F2"), 
                       values = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 135000))+
  scale_color_manual(values = manual_colors)+
  labs(title = "Error positions (Passed the threshold)",
         # subtitle = "blank for now",
         # caption = Sys.Date()
       )+
  theme(panel.border = element_rect(colour = "grey", fill=NA, size=1),   # 给图加一个边框
  
        panel.background = element_rect(fill = "#2DB600")) +
  annotate(geom = 'text', label = paste0(data_ERR_F_count, " (", round(data_ERR_F_count/nrow(data_ERR)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -1.1, vjust = 1.5, size = 5)
# 绘制第二个图形
p2 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_all)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_all), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_all)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ALL)*100, 3), "%)")),
                data = venn_region(data_all),
                size = 3) +  theme_void()+ 
  scale_fill_gradientn(colors = c("#F4FAFE", "#2DB600", "#63C600", "#A0D600", "#E6E600", "#E8C32E", "#EBB25E", "#EDB48E", "#F0C9C0", "#F2F2F2"), 
                       values = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 135000))+
  scale_color_manual(values = manual_colors)+
  labs(title = "All positions (Passed the threshold)",
         #subtitle = "blank for now",
         #caption = Sys.Date()
       )+
  theme(panel.border = element_rect(colour = "grey", fill=NA, size=1),   # 给图加一个边框
  
        panel.background = element_rect(fill = "#F0C9C0")) +
  annotate(geom = 'text', label = paste0(data_ALL_F_count, " (", round(data_ALL_F_count/nrow(data_ALL)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -0.9, vjust = 1.5, size = 5)

# 绘制第一个图形
p3 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_err_F)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_err_F), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_err_F)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR)*100, 3), "%)")),
                data = venn_region(data_err_F),
                size = 3) +  theme_void()+ 
  scale_fill_gradientn(colors = c("#F4FAFE", "#2DB600", "#63C600", "#A0D600", "#E6E600", "#E8C32E", "#EBB25E", "#EDB48E", "#F0C9C0", "#F2F2F2"), 
                       values = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 135000))+
  scale_color_manual(values = manual_colors)+
  labs(title = "Error positions (Unpassed the threshold)",
         # subtitle = "blank for now",
         # caption = Sys.Date()
       )+
  theme(panel.border = element_rect(colour = "grey", fill=NA, size=1),   # 给图加一个边框
  
        panel.background = element_rect(fill = "#2DB600")) +
annotate(geom = 'text', label = paste0(data_ERR_count, " (", round(data_ERR_count/nrow(data_ERR)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -0.95, vjust = 1.5, size = 5)

# 绘制第二个图形
p4 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_all_F)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_all_F), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_all_F)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ALL)*100, 3), "%)")),
                data = venn_region(data_all_F),
                size = 3) +  theme_void()+ 
  scale_fill_gradientn(colors = c("#F4FAFE", "#2DB600", "#63C600", "#A0D600", "#E6E600", "#E8C32E", "#EBB25E", "#EDB48E", "#F0C9C0", "#F2F2F2"), 
                       values = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 135000))+
  scale_color_manual(values = manual_colors)+
  labs(title = "All positions (Unpassed the threshold)",
         #subtitle = "blank for now",
         #caption = Sys.Date()
       )+
  theme(panel.border = element_rect(colour = "grey", fill=NA, size=1),   # 给图加一个边框
  
        panel.background = element_rect(fill = "#F4FAFE")) +
annotate(geom = 'text', label = paste0(data_ALL_count, " (", round(data_ALL_count/nrow(data_ALL)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -1.35, vjust = 1.5, size = 5)

# 创建标题
title <- ggdraw() + draw_label("Venn diagram of the indicator comparison")

# 在一个2 x 2的画布上显示四个图形
combined_plot <- plot_grid(p1, p2, p3, p4, nrow = 2, ncol = 2)

# 添加共享图例
legend <- cowplot::get_legend(
  ggplot() +
    geom_sf(aes(color = name), data = venn_setedge(data_all), show.legend = TRUE, size = 2) +
    scale_color_manual(values = manual_colors) +
    theme_void() +
    labs(color = "Category") +
    theme(legend.direction = "horizontal")
)

# 将图形和图例组合在一起
final_plot <- plot_grid(
  title,
  combined_plot, 
  legend, 
  nrow = 3, 
  rel_heights = c(0.1, 1, 0.1), 
  align = "h", 
  axis = "l"
)

# 显示最终的图形
print(final_plot)
```


```{r}
# 自定义颜色
manual_colors <- c("AF" = "orange", "SB" = "steelblue", "COV" = "red")

# 绘制第一个图形
p1 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_err)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_err), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_err)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR)*100, 3), "%)")),
                data = venn_region(data_err),
                size = 3) +  theme_void()+ 
  scale_fill_gradientn(colors = c("#D9EFFB","#B5E1F7","#ACDEF6","#A3DBF5","#9AD8F4","#91D4F3","#82C7F8","#6FBEF7","#5CB6F6","#499DF5"), 
                       values = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 300000), guide = "none")+
  scale_color_manual(values = manual_colors)+
  labs(title = "Error positions (Passed the threshold)",
         # subtitle = "blank for now",
         # caption = Sys.Date()
       )+
  theme(panel.border = element_rect(colour = "grey", fill=NA, size=1),   # 给图加一个边框
  
        panel.background = element_rect(fill = "#EBF6FD")) +
  annotate(geom = 'text', label = paste0(data_ERR_F_count, " (", round(data_ERR_F_count/nrow(data_ERR)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -1.4, vjust = 1.5, size = 5)
# 绘制第二个图形
p2 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_all)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_all), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_all)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ALL)*100, 3), "%)")),
                data = venn_region(data_all),
                size = 3) +  theme_void()+ 
  scale_fill_gradientn(colors = c("#D9EFFB","#B5E1F7","#ACDEF6","#A3DBF5","#9AD8F4","#91D4F3","#82C7F8","#6FBEF7","#5CB6F6","#499DF5"), 
                       values = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 300000), guide = "none")+
  scale_color_manual(values = manual_colors)+
  labs(title = "All positions (Passed the threshold)",
         #subtitle = "blank for now",
         #caption = Sys.Date()
       )+
  theme(panel.border = element_rect(colour = "grey", fill=NA, size=1),   # 给图加一个边框
  
        panel.background = element_rect(fill = "#6FBEF7")) +
  annotate(geom = 'text', label = paste0(data_ALL_F_count, " (", round(data_ALL_F_count/nrow(data_ALL)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -1.05, vjust = 1.5, size = 5)

# 绘制第一个图形
p3 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_err_F)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_err_F), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_err_F)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR)*100, 3), "%)")),
                data = venn_region(data_err_F),
                size = 3) +  theme_void()+ 
  scale_fill_gradientn(colors = c("#D9EFFB","#B5E1F7","#ACDEF6","#A3DBF5","#9AD8F4","#91D4F3","#82C7F8","#6FBEF7","#5CB6F6","#499DF5"), 
                       values = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 300000), guide = "none")+
  scale_color_manual(values = manual_colors)+
  labs(title = "Error positions (Unpassed the threshold)",
         # subtitle = "blank for now",
         # caption = Sys.Date()
       )+
  theme(panel.border = element_rect(colour = "grey", fill=NA, size=1),   # 给图加一个边框
  
        panel.background = element_rect(fill = "#E2F3FC")) +
annotate(geom = 'text', label = paste0(data_ERR_count, " (", round(data_ERR_count/nrow(data_ERR)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -1.55, vjust = 1.5, size = 5)

# 绘制第二个图形
p4 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_all_F)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_all_F), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_all_F)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ALL)*100, 3), "%)")),
                data = venn_region(data_all_F),
                size = 3) +  theme_void()+ 
  scale_fill_gradientn(colors = c("#D9EFFB","#B5E1F7","#ACDEF6","#A3DBF5","#9AD8F4","#91D4F3","#82C7F8","#6FBEF7","#5CB6F6","#499DF5"), 
                       values = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 300000), guide = "none")+
  scale_color_manual(values = manual_colors)+
  labs(title = "All positions (Unpassed the threshold)",
         #subtitle = "blank for now",
         #caption = Sys.Date()
       )+
  theme(panel.border = element_rect(colour = "grey", fill=NA, size=1),   # 给图加一个边框
  
        panel.background = element_rect(fill = "#F4FAFE")) +
annotate(geom = 'text', label = paste0(data_ALL_count, " (", round(data_ALL_count/nrow(data_ALL)*100, 3), "%)"), x = -Inf, y = Inf, hjust = -1.7, vjust = 1.5, size = 5)

# 创建标题
title <- ggdraw() + draw_label("Venn diagram of the indicator comparison")

# 在一个2 x 2的画布上显示四个图形
combined_plot <- plot_grid(p1, p2, p3, p4, nrow = 2, ncol = 2)

# 添加共享图例
legend <- cowplot::get_legend(
  ggplot() +
    geom_sf(aes(color = name), data = venn_setedge(data_all), show.legend = TRUE, size = 2) +
    scale_color_manual(values = manual_colors) +
    theme_void() +
    labs(color = "Category") +
    theme(legend.direction = "horizontal")
)

# 将图形和图例组合在一起
final_plot <- plot_grid(
  title,
  combined_plot, 
  legend, 
  nrow = 3, 
  rel_heights = c(0.1, 1, 0.1), 
  align = "h", 
  axis = "l"
)

# 显示最终的图形
print(final_plot)
```

P3: 0.02

```{r}
"#F4FAFE"
"#EBF6FD"
"#E2F3FC"
"#D9EFFB"## here
"#D0ECFA"
"#C7E8F9"
"#BEE5F8"
"#B5E1F7"
"#ACDEF6"
"#A3DBF5"
"#9AD8F4"
"#91D4F3"
"#88D1F2"
"#7FDDEF"
"#76DAEE"

```

### Old version

```{r}
# 自定义颜色
manual_colors <- c("AF" = "orange", "SB" = "steelblue", "COV" = "red")

# 绘制第一个图形
p1 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_err_F)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_err_F), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_err_F)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR)*100, 3), "%)")),
                data = venn_region(data_err_F),
                size = 3) +  theme_void()+ 
  scale_fill_gradientn(colors = c("#F4FAFE","#CFE9FC","#BCE1FB","#A8D8FA","#95D0F9","skyblue","#82C7F8","#6FBEF7","#5CB6F6","#499DF5"), 
                       values = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 300000), guide = "none")+
  scale_color_manual(values = manual_colors)+
  labs(title = "Error positions' Venn Diagram",
         # subtitle = "blank for now",
         # caption = Sys.Date()
       )

# 绘制第二个图形
p2 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_all_F)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_all_F), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_all_F)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ALL)*100, 3), "%)")),
                data = venn_region(data_all_F),
                size = 3) +  theme_void()+ 
  scale_fill_gradientn(colors = c("#F4FAFE","#CFE9FC","#BCE1FB","#A8D8FA","#95D0F9","skyblue","#82C7F8","#6FBEF7","#5CB6F6","#499DF5"), 
                       values = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), limits = c(0, 300000), guide = "none")+
  scale_color_manual(values = manual_colors)+
  labs(title = "All positions' Venn Diagram",
         #subtitle = "blank for now",
         #caption = Sys.Date()
       )

# 在一个1 x 2的画布上显示两个图形
combined_plot <- plot_grid(p1, p2, ncol = 2)

# 添加共享图例
legend <- cowplot::get_legend(
  ggplot() +
    geom_sf(aes(color = name), data = venn_setedge(data_all), show.legend = TRUE, size = 2) +
    scale_color_manual(values = manual_colors) +
    theme_void() +
    labs(color = "Category") +
    theme(legend.direction = "horizontal")
)

# 将图形和图例组合在一起
final_plot <- plot_grid(
  combined_plot, 
  NULL, 
  legend, 
  nrow = 3, 
  rel_heights = c(2, 0.01, 0.1), 
  align = "h", 
  axis = "l"
)

# 显示最终的图形
print(final_plot)


```



```{r}
# 定义函数来统计不同条件下的个数
count_true <- function(data, col_AF, col_SB, col_COV) {
  # 转换相关列为逻辑值
  data[[col_AF]] <- as.logical(data[[col_AF]])
  data[[col_SB]] <- as.logical(data[[col_SB]])
  data[[col_COV]] <- as.logical(data[[col_COV]])

  # 统计不同条件下的个数
  only_AF_true_count <- sum(data[[col_AF]])
  only_SB_true_count <- sum(data[[col_SB]])
  only_COV_true_count <- sum(data[[col_COV]])

  AF_SB_true_count <- (sum(!data[[col_AF]]) + sum(!data[[col_SB]]))/2
  SB_COV_true_count <- (sum(!data[[col_SB]]) + sum(!data[[col_COV]]))/2
  AF_COV_true_count <- (sum(!data[[col_AF]]) + sum(!data[[col_COV]]))/2

  three_true_count <- (sum(!data[[col_AF]]) + sum(!data[[col_SB]]) + sum(!data[[col_COV]]))/3

  # 返回结果
  return(list(
    only_AF = only_AF_true_count,
    only_SB = only_SB_true_count,
    only_COV = only_COV_true_count,
    AF_SB = AF_SB_true_count,
    SB_COV = SB_COV_true_count,
    AF_COV = AF_COV_true_count,
    three_true = three_true_count
  ))
}
```


```{r}
# Convert relevant columns to logical values
data_ALL$Flag_AF <- as.logical(data_ALL$Flag_AF)
data_ALL$Flag_SB <- as.logical(data_ALL$Flag_SB)
data_ALL$Flag_COV <- as.logical(data_ALL$Flag_COV)

# 统计一列均为True的个数
only_AF_true_count_all <- sum(!data_ALL$Flag_AF)
only_SB_true_count_all <- sum(!data_ALL$Flag_SB)
only_COV_true_count_all <- sum(!data_ALL$Flag_COV)

# 统计两列均为True的个数
AF_SB_true_count_all <- sum(data_ALL$Flag_AF & data_ALL$Flag_SB & !data_ALL$Flag_COV)
SB_COV_true_count_all <- sum(!data_ALL$Flag_AF & data_ALL$Flag_SB & data_ALL$Flag_COV)
AF_COV_true_count_all <- sum(data_ALL$Flag_AF & !data_ALL$Flag_SB & data_ALL$Flag_COV)

# 统计三列均为True的个数
three_true_count_all <- sum(data_ALL$Flag_AF & data_ALL$Flag_SB & data_ALL$Flag_COV)

# 打印结果
cat("仅Flag_AF为False的个数：", only_AF_true_count_all, "\n")
cat("仅Flag_SB为False的个数：", only_SB_true_count_all, "\n")
cat("仅Flag_COV为False的个数：", only_COV_true_count_all, "\n")

cat("AF和SB为True的个数：", AF_SB_true_count_all, "\n")
cat("SB和COV为True的个数：", SB_COV_true_count_all, "\n")
cat("AF和COV为True的个数：", AF_COV_true_count_all, "\n")

cat("三列均为True的个数：", three_true_count_all, "\n")
```

```{r}
# Convert relevant columns to logical values
data_ERR$Flag_AF <- as.logical(data_ERR$Flag_AF)
data_ERR$Flag_SB <- as.logical(data_ERR$Flag_SB)
data_ERR$Flag_COV <- as.logical(data_ERR$Flag_COV)

# 统计一列均为True的个数
only_AF_true_count <- sum(!data_ERR$Flag_AF)
only_SB_true_count <- sum(!data_ERR$Flag_SB)
only_COV_true_count <- sum(!data_ERR$Flag_COV)

# 统计两列均为True的个数
AF_SB_true_count <- sum(data_ERR$Flag_AF & data_ERR$Flag_SB & !data_ERR$Flag_COV)
SB_COV_true_count <- sum(!data_ERR$Flag_AF & data_ERR$Flag_SB & data_ERR$Flag_COV)
AF_COV_true_count <- sum(data_ERR$Flag_AF & !data_ERR$Flag_SB & data_ERR$Flag_COV)

# 统计三列均为True的个数
three_true_count <- sum(data_ERR$Flag_AF & data_ERR$Flag_SB & data_ERR$Flag_COV)

# 打印结果
cat("仅Flag_AF为False的个数：", only_AF_true_count, "\n")
cat("仅Flag_SB为False的个数：", only_SB_true_count, "\n")
cat("仅Flag_COV为False的个数：", only_COV_true_count, "\n")

cat("AF和SB为True的个数：", AF_SB_true_count, "\n")
cat("SB和COV为True的个数：", SB_COV_true_count, "\n")
cat("AF和COV为True的个数：", AF_COV_true_count, "\n")

cat("三列均为True的个数：", three_true_count, "\n")
```
```{r}
# 统计一列均为True的个数
only_AF_true_count <- sum(!data_ERR$Flag_AF)
only_SB_true_count <- sum(!data_ERR$Flag_SB)
only_COV_true_count <- sum(!data_ERR$Flag_COV)

# 统计两列均为True的个数
AF_SB_true_count <- sum(data_ERR$Flag_AF) + sum(data_ERR$Flag_SB)
SB_COV_true_count <- sum(data_ERR$Flag_SB) + sum(data_ERR$Flag_COV)
AF_COV_true_count <- sum(data_ERR$Flag_AF) + sum(data_ERR$Flag_COV)

# 统计三列均为True的个数
three_true_count <- sum(data_ERR$Flag_AF & data_ERR$Flag_SB & data_ERR$Flag_COV)

# 打印结果
cat("仅Flag_AF为False的个数：", only_AF_true_count, "\n")
cat("仅Flag_SB为False的个数：", only_SB_true_count, "\n")
cat("仅Flag_COV为False的个数：", only_COV_true_count, "\n")

cat("AF和SB为True的个数：", AF_SB_true_count, "\n")
cat("SB和COV为True的个数：", SB_COV_true_count, "\n")
cat("AF和COV为True的个数：", AF_COV_true_count, "\n")

cat("三列均为True的个数：", three_true_count, "\n")
```

## 2. For T-F
```{r}

# 统计全部数据框的个数
count_all <- count_true(data_ALL, "Flag_AF", "Flag_SB", "Flag_COV")

# 打印全部数据框的结果
cat("全部数据框中的结果：\n")
cat("仅Flag_AF为False的个数：", count_all$only_AF, "\n")
cat("仅Flag_SB为False的个数：", count_all$only_SB, "\n")
cat("仅Flag_COV为False的个数：", count_all$only_COV, "\n")
cat("AF和SB为True的个数：", count_all$AF_SB, "\n")
cat("SB和COV为True的个数：", count_all$SB_COV, "\n")
cat("AF和COV为True的个数：", count_all$AF_COV, "\n")
cat("三列均为True的个数：", count_all$three_true, "\n")

# 统计数据框 data_ERR 的个数
count_err <- count_true(data_ERR, "Flag_AF", "Flag_SB", "Flag_COV")

# 打印数据框 data_ERR 的结果
cat("数据框 data_ERR 的结果：\n")
cat("仅Flag_AF为False的个数：", count_err$only_AF, "\n")
cat("仅Flag_SB为False的个数：", count_err$only_SB, "\n")
cat("仅Flag_COV为False的个数：", count_err$only_COV, "\n")
cat("AF和SB为True的个数：", count_err$AF_SB, "\n")
cat("SB和COV为True的个数：", count_err$SB_COV, "\n")
cat("AF和COV为True的个数：", count_err$AF_COV, "\n")
cat("三列均为True的个数：", count_err$three_true, "\n")

```


```{r}
data_err@region[["count"]][1] <- round(count_err$only_AF, 0)
data_err@region[["count"]][2] <- round(count_err$only_SB, 0)
data_err@region[["count"]][3] <- round(count_err$only_COV, 0)
data_err@region[["count"]][4] <- round(count_err$AF_SB, 0)
data_err@region[["count"]][5] <- round(count_err$AF_COV, 0)
data_err@region[["count"]][6] <- round(count_err$SB_COV, 0)
data_err@region[["count"]][7] <- round(count_err$three_true, 0)

data_all@region[["count"]][1] <- round(count_all$only_AF, 0)
data_all@region[["count"]][2] <- round(count_all$only_SB, 0)
data_all@region[["count"]][3] <- round(count_all$only_COV, 0)
data_all@region[["count"]][4] <- round(count_all$AF_SB, 0)
data_all@region[["count"]][5] <- round(count_all$AF_COV, 0)
data_all@region[["count"]][6] <- round(count_all$SB_COV, 0)
data_all@region[["count"]][7] <- round(count_all$three_true, 0)
```


```{r}
# 自定义颜色
manual_colors <- c("AF" = "orange", "SB" = "steelblue", "COV" = "red")

# 绘制第一个图形
p1 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_err)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_err), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_err)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ERR)*100, 3), "%)")),
                data = venn_region(data_err),
                size = 3) +  theme_void()+ 
  scale_fill_gradient(low = "#F4FAFE", high = "skyblue") +
  scale_color_manual(values = manual_colors)+
  labs(title = "Error positions' Venn Diagram",
         # subtitle = "blank for now",
         # caption = Sys.Date()
       )

# 绘制第二个图形
p2 <- ggplot() +
  # 1. region count layer
  geom_sf(aes(fill = count), data = venn_region(data_all)) +
  # 2. set edge layer
  geom_sf(aes(color = name), data = venn_setedge(data_all), show.legend = FALSE, size = 2) +
  # 3. set label layer
  geom_sf_text(aes(label = ifelse(name %in% c("AF", "SB", "COV"), "", name)), data = venn_setlabel(data_all)) +
  # 4. region label layer
  geom_sf_label(aes(label = paste0(count, " (", round(count/nrow(data_ALL)*100, 3), "%)")),
                data = venn_region(data_all),
                size = 3) +  theme_void()+ 
  scale_fill_gradient(low = "#F4FAFE", high = "skyblue") +
  scale_color_manual(values = manual_colors)+
  labs(title = "All positions' Venn Diagram",
         #subtitle = "blank for now",
         #caption = Sys.Date()
       )

# 在一个1 x 2的画布上显示两个图形
combined_plot <- plot_grid(p1, p2, ncol = 2)

# 添加共享图例
legend <- cowplot::get_legend(
  ggplot() +
    geom_sf(aes(color = name), data = venn_setedge(data_all), show.legend = TRUE, size = 2) +
    scale_color_manual(values = manual_colors) +
    theme_void() +
    labs(color = "Category") +
    theme(legend.direction = "horizontal")
)

# 将图形和图例组合在一起
final_plot <- plot_grid(
  combined_plot, 
  NULL, 
  legend, 
  nrow = 3, 
  rel_heights = c(2, 0.01, 0.1), 
  align = "h", 
  axis = "l"
)

# 显示最终的图形
print(final_plot)

```

